devTools:
  dataInspector:
    variables:
      travel-times: Travel times
      green-spaces-proximity: Green space prox
      green-spaces-areas: Green space areas
      pollution: Pollution (all)
      pollution-residential: Pollution (resid.)
      noise: Noise (all)
      noise-residential: Noise (resid.)
